---
- name: Register home directory for {{ user }}
  getent:
    database: passwd
    key: '{{ user }}'
    split: ':'

- name: Set facts
  set_fact:
    user_home: "{{ getent_passwd[user][4] }}"
    user_shell: "{{ getent_passwd[user][5] }}"
